#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l vmem=6gb
#PBS -l walltime=01:00:00
#PBS -N app-network-backbone

# set -e
# set -x

SINGULARITYENV_PYTHONNOUSERSITE=true
time singularity exec -e docker://brainlife/python-networks ./main.py
